# -*- coding: utf-8 -*-
"""datacleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k5D0kbWje1Fp3w55CXbS2HUa9FZ86BGf
"""

import pandas as pd
url='https://raw.githubusercontent.com/Jcharis/Data-Cleaning-Practical-Examples/master/unclean_data1.csv'
cleaning=pd.read_csv(url)
cleaning

cleaning.head()

cleaning.describe()

cleaning.info()

cleaning.isnull().sum()

numeric_cols = cleaning.select_dtypes(include=['number']).columns
cleaning[numeric_cols] = cleaning[numeric_cols].fillna(cleaning[numeric_cols].mean())

non_numeric_cols = cleaning.select_dtypes(exclude=['number']).columns
cleaning[non_numeric_cols] = cleaning[non_numeric_cols].fillna(cleaning[non_numeric_cols].mode().iloc[0])

cleaning.drop_duplicates(inplace=True)

cleaning.to_csv('cleaned_data.csv', index=False)

print("\nCleaned Data:")
print(cleaning.head())

cleaning.isnull().sum()

cleaning